/* Automatically generated by util/errno.alo -- DO NOT MODIFY! */

#include "aconfig.h"
#include "errno_module.h"
#include <errno.h>

AErrnoEntry AErrnoTable[] = {
#ifdef E2BIG
    { A_ERRNO_E2BIG, E2BIG, "Argument list too long" },
#else
    { A_ERRNO_E2BIG, 0, 0 },
#endif
#ifdef EACCES
    { A_ERRNO_EACCES, EACCES, "Permission denied" },
#else
    { A_ERRNO_EACCES, 0, 0 },
#endif
#ifdef EADDRINUSE
    { A_ERRNO_EADDRINUSE, EADDRINUSE, "Address in use" },
#else
    { A_ERRNO_EADDRINUSE, 0, 0 },
#endif
#ifdef EADDRNOTAVAIL
    { A_ERRNO_EADDRNOTAVAIL, EADDRNOTAVAIL, "Local address not available" },
#else
    { A_ERRNO_EADDRNOTAVAIL, 0, 0 },
#endif
#ifdef EAFNOSUPPORT
    { A_ERRNO_EAFNOSUPPORT, EAFNOSUPPORT, "Address family not supported" },
#else
    { A_ERRNO_EAFNOSUPPORT, 0, 0 },
#endif
#ifdef EAGAIN
    { A_ERRNO_EAGAIN, EAGAIN, "Resource temporarily unavailable" },
#else
    { A_ERRNO_EAGAIN, 0, 0 },
#endif
#ifdef EBADF
    { A_ERRNO_EBADF, EBADF, "Bad file descriptor" },
#else
    { A_ERRNO_EBADF, 0, 0 },
#endif
#ifdef EBADFD
    { A_ERRNO_EBADFD, EBADFD, "File descriptor in bad state" },
#else
    { A_ERRNO_EBADFD, 0, 0 },
#endif
#ifdef EBUSY
    { A_ERRNO_EBUSY, EBUSY, "Resource busy" },
#else
    { A_ERRNO_EBUSY, 0, 0 },
#endif
#ifdef ECANCELED
    { A_ERRNO_ECANCELED, ECANCELED, "Operation canceled" },
#else
    { A_ERRNO_ECANCELED, 0, 0 },
#endif
#ifdef ECHILD
    { A_ERRNO_ECHILD, ECHILD, "No child processes" },
#else
    { A_ERRNO_ECHILD, 0, 0 },
#endif
#ifdef ECOMM
    { A_ERRNO_ECOMM, ECOMM, "Communication error on send" },
#else
    { A_ERRNO_ECOMM, 0, 0 },
#endif
#ifdef ECONNABORTED
    { A_ERRNO_ECONNABORTED, ECONNABORTED, "Connection aborted" },
#else
    { A_ERRNO_ECONNABORTED, 0, 0 },
#endif
#ifdef ECONNREFUSED
    { A_ERRNO_ECONNREFUSED, ECONNREFUSED, "Connection refused" },
#else
    { A_ERRNO_ECONNREFUSED, 0, 0 },
#endif
#ifdef EDEADLK
    { A_ERRNO_EDEADLK, EDEADLK, "Resource deadlock avoided" },
#else
    { A_ERRNO_EDEADLK, 0, 0 },
#endif
#ifdef EDOM
    { A_ERRNO_EDOM, EDOM, "Domain error" },
#else
    { A_ERRNO_EDOM, 0, 0 },
#endif
#ifdef EEXIST
    { A_ERRNO_EEXIST, EEXIST, "File exists" },
#else
    { A_ERRNO_EEXIST, 0, 0 },
#endif
#ifdef EFAULT
    { A_ERRNO_EFAULT, EFAULT, "Bad address" },
#else
    { A_ERRNO_EFAULT, 0, 0 },
#endif
#ifdef EFBIG
    { A_ERRNO_EFBIG, EFBIG, "File too large" },
#else
    { A_ERRNO_EFBIG, 0, 0 },
#endif
#ifdef EHOSTDOWN
    { A_ERRNO_EHOSTDOWN, EHOSTDOWN, "Host is down" },
#else
    { A_ERRNO_EHOSTDOWN, 0, 0 },
#endif
#ifdef EHOSTUNREACH
    { A_ERRNO_EHOSTUNREACH, EHOSTUNREACH, "Host in unreachable" },
#else
    { A_ERRNO_EHOSTUNREACH, 0, 0 },
#endif
#ifdef EIDRM
    { A_ERRNO_EIDRM, EIDRM, "Identifier removed" },
#else
    { A_ERRNO_EIDRM, 0, 0 },
#endif
#ifdef EILSEQ
    { A_ERRNO_EILSEQ, EILSEQ, "Illegal byte sequence" },
#else
    { A_ERRNO_EILSEQ, 0, 0 },
#endif
#ifdef EINPROGRESS
    { A_ERRNO_EINPROGRESS, EINPROGRESS, "Operation in progress" },
#else
    { A_ERRNO_EINPROGRESS, 0, 0 },
#endif
#ifdef EINTR
    { A_ERRNO_EINTR, EINTR, "Interrupted function call" },
#else
    { A_ERRNO_EINTR, 0, 0 },
#endif
#ifdef EINVAL
    { A_ERRNO_EINVAL, EINVAL, "Invalid argument" },
#else
    { A_ERRNO_EINVAL, 0, 0 },
#endif
#ifdef EIO
    { A_ERRNO_EIO, EIO, "Input/output error" },
#else
    { A_ERRNO_EIO, 0, 0 },
#endif
#ifdef EISCONN
    { A_ERRNO_EISCONN, EISCONN, "Socket is connected" },
#else
    { A_ERRNO_EISCONN, 0, 0 },
#endif
#ifdef EISDIR
    { A_ERRNO_EISDIR, EISDIR, "Is a directory" },
#else
    { A_ERRNO_EISDIR, 0, 0 },
#endif
#ifdef ELOOP
    { A_ERRNO_ELOOP, ELOOP, "Too many levels of symbolic links" },
#else
    { A_ERRNO_ELOOP, 0, 0 },
#endif
#ifdef EMFILE
    { A_ERRNO_EMFILE, EMFILE, "Too many open files" },
#else
    { A_ERRNO_EMFILE, 0, 0 },
#endif
#ifdef EMLINK
    { A_ERRNO_EMLINK, EMLINK, "Too many links" },
#else
    { A_ERRNO_EMLINK, 0, 0 },
#endif
#ifdef EMSGSIZE
    { A_ERRNO_EMSGSIZE, EMSGSIZE, "Message too long" },
#else
    { A_ERRNO_EMSGSIZE, 0, 0 },
#endif
#ifdef ENAMETOOLONG
    { A_ERRNO_ENAMETOOLONG, ENAMETOOLONG, "Filename too long" },
#else
    { A_ERRNO_ENAMETOOLONG, 0, 0 },
#endif
#ifdef ENETDOWN
    { A_ERRNO_ENETDOWN, ENETDOWN, "Network is down" },
#else
    { A_ERRNO_ENETDOWN, 0, 0 },
#endif
#ifdef ENETUNREACH
    { A_ERRNO_ENETUNREACH, ENETUNREACH, "Network unreachable" },
#else
    { A_ERRNO_ENETUNREACH, 0, 0 },
#endif
#ifdef ENFILE
    { A_ERRNO_ENFILE, ENFILE, "Too many open files" },
#else
    { A_ERRNO_ENFILE, 0, 0 },
#endif
#ifdef ENODEV
    { A_ERRNO_ENODEV, ENODEV, "No such device" },
#else
    { A_ERRNO_ENODEV, 0, 0 },
#endif
#ifdef ENOENT
    { A_ERRNO_ENOENT, ENOENT, "No such file or directory" },
#else
    { A_ERRNO_ENOENT, 0, 0 },
#endif
#ifdef ENOEXEC
    { A_ERRNO_ENOEXEC, ENOEXEC, "Exec format error" },
#else
    { A_ERRNO_ENOEXEC, 0, 0 },
#endif
#ifdef ENOLCK
    { A_ERRNO_ENOLCK, ENOLCK, "No locks available" },
#else
    { A_ERRNO_ENOLCK, 0, 0 },
#endif
#ifdef ENOLINK
    { A_ERRNO_ENOLINK, ENOLINK, "Link has been severed" },
#else
    { A_ERRNO_ENOLINK, 0, 0 },
#endif
#ifdef ENOMEM
    { A_ERRNO_ENOMEM, ENOMEM, "Not enough space" },
#else
    { A_ERRNO_ENOMEM, 0, 0 },
#endif
#ifdef ENOMSG
    { A_ERRNO_ENOMSG, ENOMSG, "No message of the desired type" },
#else
    { A_ERRNO_ENOMSG, 0, 0 },
#endif
#ifdef ENONET
    { A_ERRNO_ENONET, ENONET, "Machine is not on the network" },
#else
    { A_ERRNO_ENONET, 0, 0 },
#endif
#ifdef ENOPROTOOPT
    { A_ERRNO_ENOPROTOOPT, ENOPROTOOPT, "Protocol not available" },
#else
    { A_ERRNO_ENOPROTOOPT, 0, 0 },
#endif
#ifdef ENOSPC
    { A_ERRNO_ENOSPC, ENOSPC, "No space left on device" },
#else
    { A_ERRNO_ENOSPC, 0, 0 },
#endif
#ifdef ENOSR
    { A_ERRNO_ENOSR, ENOSR, "No STREAM resources" },
#else
    { A_ERRNO_ENOSR, 0, 0 },
#endif
#ifdef ENOSTR
    { A_ERRNO_ENOSTR, ENOSTR, "Not a STREAM" },
#else
    { A_ERRNO_ENOSTR, 0, 0 },
#endif
#ifdef ENOSYS
    { A_ERRNO_ENOSYS, ENOSYS, "Function not implemented" },
#else
    { A_ERRNO_ENOSYS, 0, 0 },
#endif
#ifdef ENOTCONN
    { A_ERRNO_ENOTCONN, ENOTCONN, "Socket is not connected" },
#else
    { A_ERRNO_ENOTCONN, 0, 0 },
#endif
#ifdef ENOTDIR
    { A_ERRNO_ENOTDIR, ENOTDIR, "Not a directory" },
#else
    { A_ERRNO_ENOTDIR, 0, 0 },
#endif
#ifdef ENOTEMPTY
    { A_ERRNO_ENOTEMPTY, ENOTEMPTY, "Directory not empty" },
#else
    { A_ERRNO_ENOTEMPTY, 0, 0 },
#endif
#ifdef ENOTSOCK
    { A_ERRNO_ENOTSOCK, ENOTSOCK, "Not a socket" },
#else
    { A_ERRNO_ENOTSOCK, 0, 0 },
#endif
#ifdef ENOTSUP
    { A_ERRNO_ENOTSUP, ENOTSUP, "Operation not supported" },
#else
    { A_ERRNO_ENOTSUP, 0, 0 },
#endif
#ifdef ENOTTY
    { A_ERRNO_ENOTTY, ENOTTY, "Inappropriate I/O control operation" },
#else
    { A_ERRNO_ENOTTY, 0, 0 },
#endif
#ifdef ENOTUNIQ
    { A_ERRNO_ENOTUNIQ, ENOTUNIQ, "Name not unique on network" },
#else
    { A_ERRNO_ENOTUNIQ, 0, 0 },
#endif
#ifdef ENXIO
    { A_ERRNO_ENXIO, ENXIO, "No such device or address" },
#else
    { A_ERRNO_ENXIO, 0, 0 },
#endif
#ifdef EOPNOTSUPP
    { A_ERRNO_EOPNOTSUPP, EOPNOTSUPP, "Operation not supported" },
#else
    { A_ERRNO_EOPNOTSUPP, 0, 0 },
#endif
#ifdef EOVERFLOW
    { A_ERRNO_EOVERFLOW, EOVERFLOW, "Value too large to be stored in data type" },
#else
    { A_ERRNO_EOVERFLOW, 0, 0 },
#endif
#ifdef EPERM
    { A_ERRNO_EPERM, EPERM, "Operation not permitted" },
#else
    { A_ERRNO_EPERM, 0, 0 },
#endif
#ifdef EPIPE
    { A_ERRNO_EPIPE, EPIPE, "Broken pipe" },
#else
    { A_ERRNO_EPIPE, 0, 0 },
#endif
#ifdef EPROTO
    { A_ERRNO_EPROTO, EPROTO, "Protocol error" },
#else
    { A_ERRNO_EPROTO, 0, 0 },
#endif
#ifdef EPROTONOSUPPORT
    { A_ERRNO_EPROTONOSUPPORT, EPROTONOSUPPORT, "Protocol not supported" },
#else
    { A_ERRNO_EPROTONOSUPPORT, 0, 0 },
#endif
#ifdef EPROTOTYPE
    { A_ERRNO_EPROTOTYPE, EPROTOTYPE, "Protocol wrong type for socket" },
#else
    { A_ERRNO_EPROTOTYPE, 0, 0 },
#endif
#ifdef ERANGE
    { A_ERRNO_ERANGE, ERANGE, "Result too large" },
#else
    { A_ERRNO_ERANGE, 0, 0 },
#endif
#ifdef ERESTART
    { A_ERRNO_ERESTART, ERESTART, "Interrupted system call should be restarted" },
#else
    { A_ERRNO_ERESTART, 0, 0 },
#endif
#ifdef EROFS
    { A_ERRNO_EROFS, EROFS, "Read-only file system" },
#else
    { A_ERRNO_EROFS, 0, 0 },
#endif
#ifdef ESPIPE
    { A_ERRNO_ESPIPE, ESPIPE, "Invalid seek" },
#else
    { A_ERRNO_ESPIPE, 0, 0 },
#endif
#ifdef ESRCH
    { A_ERRNO_ESRCH, ESRCH, "No such process" },
#else
    { A_ERRNO_ESRCH, 0, 0 },
#endif
#ifdef ESTALE
    { A_ERRNO_ESTALE, ESTALE, "Stale file handle" },
#else
    { A_ERRNO_ESTALE, 0, 0 },
#endif
#ifdef ETIME
    { A_ERRNO_ETIME, ETIME, "Timer expired" },
#else
    { A_ERRNO_ETIME, 0, 0 },
#endif
#ifdef ETIMEDOUT
    { A_ERRNO_ETIMEDOUT, ETIMEDOUT, "Operation timed out" },
#else
    { A_ERRNO_ETIMEDOUT, 0, 0 },
#endif
#ifdef ETXTBSY
    { A_ERRNO_ETXTBSY, ETXTBSY, "Text file busy" },
#else
    { A_ERRNO_ETXTBSY, 0, 0 },
#endif
#ifdef EWOULDBLOCK
    { A_ERRNO_EWOULDBLOCK, EWOULDBLOCK, "Operation would block" },
#else
    { A_ERRNO_EWOULDBLOCK, 0, 0 },
#endif
#ifdef EXDEV
    { A_ERRNO_EXDEV, EXDEV, "Improper link" },
#else
    { A_ERRNO_EXDEV, 0, 0 },
#endif
    { 0, 0, 0 }
};
